[build]
target = "thumbv6m-none-eabi"

[unstable]
build-std = ["alloc", "core", "compiler_builtins"]

[target.thumbv6m-none-eabi]
runner = "probe-rs run --chip RP2040"
rustflags = [
    # Linker script supplied by cortex-m-rt (standard ARM Embedded ABI + memory map)
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
    # defmt log section
    "-C", "link-arg=-Tdefmt.x",
    # Frame pointers for readable backtraces in probe-rs
    "-C", "force-frame-pointers",
]
